{
 "title": "PV Monitor",
 "time": { "from": "now/d", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "PV panels statistics",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "SolarTime{}", "legendFormat": "{{GenerationTime}}" },
    { "expr": "SolarProduction_watts_total{}", "legendFormat": "{{Production}}1" }
   ]
  },
  {
   "title": "Output Power",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "OutputPower_watts{Power=\"Active\"}",
     "legendFormat": "Power"
    }
   ]
  },
  {
   "title": "Output voltage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    { "expr": "OutputVoltage_volts{}", "legendFormat": "{{Voltage}}" }
   ]
  },
  {
   "title": "Today's production",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "delta(SolarProduction_watts_total{Production=\"Today\"}[30m])"
    }
   ]
  },
  {
   "title": "Generated monthly",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "delta(SolarProduction_watts_total{Production=\"Total\"}[1w])"
    }
   ]
  },
  {
   "title": "Inverter's temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "InverterTemp_celsius{}", "legendFormat": "{{Temp}}" }
   ]
  },
  {
   "title": "String's parameters (voltage, current)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    { "expr": "SolarVoltage_volts{}", "legendFormat": "{{Voltage}} (V)" },
    { "expr": "SolarCurrent_ampers{}", "legendFormat": "{{Current}} (A)" }
   ]
  },
  {
   "title": "Insulation to ground",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    { "expr": "InverterInsulation{}", "legendFormat": "{{Insulation2Ground}}" }
   ]
  }
 ]
}