{
 "title": "PV Monitor",
 "time": { "from": "now/d", "to": "now" },
 "panels": [
  {
   "title": "PV panels statistics",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Today's production",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "InverterData",
     "query": "SELECT max(\"SolarProduction_Today\") FROM \"InverterData\" WHERE $timeFilter fill(null)",
     "select": [
      [
       { "params": [ "SolarProduction_Today" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Total production",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "InverterData",
     "query": "SELECT sum(\"max\") FROM (SELECT max(\"SolarProduction_Today\") FROM \"InverterData\" WHERE time <= now() GROUP BY time(1d) fill(null) tz('Europe/Warsaw'))",
     "select": [
      [
       { "params": [ "SolarProduction_Today" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Current power",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "InverterData",
     "query": "SELECT \"OutputPower_Active\" FROM \"InverterData\" WHERE $timeFilter fill(null)",
     "select": [
      [
       { "params": [ "OutputPower_Active" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Today's working time",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "InverterData",
     "query": "SELECT max(\"SolarTime_Today\") FROM \"InverterData\" WHERE time>now()-5m fill(null)",
     "select": [
      [
       { "params": [ "SolarTime_Today" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Total working time",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "InverterData",
     "query": "SELECT max(\"SolarTime_Total\") FROM \"InverterData\" WHERE time>now()-5m fill(null)",
     "select": [
      [
       { "params": [ "SolarTime_Total" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Power",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "Power",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "InverterData",
     "query": "SELECT \"OutputPower_Active\" FROM \"InverterData\" WHERE $timeFilter fill(null)",
     "select": [
      [
       { "params": [ "OutputPower_Active" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Output voltage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "InverterData",
     "query": "SELECT \"OutputVoltage_L1\", \"OutputVoltage_L2\", \"OutputVoltage_L3\" FROM \"InverterData\" WHERE $timeFilter fill(null)",
     "select": [
      [
       { "params": [ "OutputVoltage_L1" ], "type": "field" }
      ],
      [
       { "params": [ "OutputVoltage_L2" ], "type": "field" }
      ],
      [
       { "params": [ "OutputVoltage_L3" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Today's production",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "alias": "Production",
     "groupBy": [
      { "params": [ "30m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "InverterData",
     "query": "SELECT difference(max(\"SolarProduction_Today\")) FROM \"InverterData\" WHERE $timeFilter GROUP BY time(30m) fill(null)",
     "select": [
      [
       { "params": [ "SolarProduction_Today" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Daily production",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "alias": "Production",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SolarPV",
     "query": "SELECT max(\"SolarProduction_Today\") FROM \"InverterData\" WHERE $timeFilter GROUP BY time(1d) fill(null) tz('Europe/Warsaw')",
     "select": [
      [
       { "params": [ "YieldToday" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tz": "Europe/Warsaw"
    }
   ]
  },
  {
   "title": "Monthly production",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "Production",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SolarPV",
     "query": "SELECT sum(\"max\") FROM (SELECT max(\"SolarProduction_Today\") FROM \"InverterData\" WHERE $timeFilter GROUP BY time(1d) fill(null) tz('Europe/Warsaw')) GROUP BY time(30d)",
     "select": [
      [
       { "params": [ "YieldToday" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tz": "Europe/Warsaw"
    }
   ]
  },
  {
   "title": "Daily working time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "alias": "Daily working time",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "InverterData",
     "query": "SELECT max(\"SolarTime_Today\") FROM \"InverterData\" WHERE $timeFilter GROUP BY time(1d) fill(null) tz('Europe/Warsaw')",
     "select": [
      [
       { "params": [ "SolarTime_Today" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Max output voltage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "alias": "L1",
     "measurement": "InverterData",
     "query": "SELECT max(\"OutputVoltage_L1\") FROM \"InverterData\" WHERE $timeFilter GROUP BY time(1d)",
     "select": [
      [
       { "params": [ "OutputVoltage_L1" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "L2 ",
     "measurement": "InverterData",
     "query": "SELECT max(\"OutputVoltage_L2\") FROM \"InverterData\" WHERE $timeFilter GROUP BY time(1d)",
     "select": [
      [
       { "params": [ "OutputVoltage_L1" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "L3",
     "measurement": "InverterData",
     "query": "SELECT max(\"OutputVoltage_L3\") FROM \"InverterData\" WHERE $timeFilter GROUP BY time(1d)",
     "select": [
      [
       { "params": [ "OutputVoltage_L1" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "String's parameters (voltage, current)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "InverterData",
     "query": "SELECT \"SolarVoltage_PV1\", \"SolarVoltage_PV2\" FROM \"InverterData\" WHERE $timeFilter fill(null)",
     "select": [
      [
       { "params": [ "SolarVoltage_PV1" ], "type": "field" }
      ],
      [
       { "params": [ "SolarVoltage_PV2" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "InverterData",
     "query": "SELECT \"SolarCurrent_PV1\", \"SolarCurrent_PV2\" FROM \"InverterData\" WHERE $timeFilter fill(null)",
     "select": [
      [
       { "params": [ "SolarCurrent_PV1" ], "type": "field" }
      ],
      [
       { "params": [ "SolarCurrent_PV2" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Inverter's temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "InverterData",
     "query": "SELECT \"InverterTemp_Inner\", \"InverterTemp_Module\" FROM \"InverterData\" WHERE $timeFilter fill(null)",
     "select": [
      [
       { "params": [ "InverterTemp_Inner" ], "type": "field" }
      ],
      [
       { "params": [ "InverterTemp_Module" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}