{
 "title": "Panele Fotowoltaiczne",
 "time": { "from": "now/d", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Statystyka pracy paneli",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "SolarTime{}", "legendFormat": "{{GenerationTime}}" },
    { "expr": "SolarProduction_watts_total{}", "legendFormat": "{{Production}}1" }
   ]
  },
  {
   "title": "Generowana moc",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "OutputPower_watts{Power=\"Active\"}",
     "legendFormat": "Moc"
    }
   ]
  },
  {
   "title": "Napięcia wyjściowe",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    { "expr": "OutputVoltage_volts{}", "legendFormat": "{{Voltage}}" }
   ]
  },
  {
   "title": "Dzisiejsza produkcja energii",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "delta(SolarProduction_watts_total{Production=\"Today\"}[30m])"
    }
   ]
  },
  {
   "title": "Miesięczna produkcja energii",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "delta(SolarProduction_watts_total{Production=\"Total\"}[1w])"
    }
   ]
  },
  {
   "title": "Temperatura falownika",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "InverterTemp_celsius{}", "legendFormat": "{{Temp}}" }
   ]
  },
  {
   "title": "Parametry stringów (napięcie, prąd)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    { "expr": "SolarVoltage_volts{}", "legendFormat": "{{Voltage}} (V)" },
    { "expr": "SolarCurrent_ampers{}", "legendFormat": "{{Current}} (A)" }
   ]
  },
  {
   "title": "Izolacja wzgędem ziemi",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    { "expr": "InverterInsulation{}", "legendFormat": "{{Insulation2Ground}}" }
   ]
  }
 ]
}